steps:
- script: 'python -m pip install --upgrade pip setuptools wheel && python -m pip install -e .[tests] --upgrade'
  displayName: Upgrade Pip & Install Pipenv
  env:
    PYTHONWARNINGS: 'ignore:DEPRECATION'
