parameters:
  vmImage:

jobs:
- job: Test_Primary
  displayName: Test Primary
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 4
    matrix:
      Python27:
        python.version: '2.7'
        python.architecture: x64
      Python37:
        python.version: '>= 3.7'
        python.architecture: x64
      Python36:
        python.version: '>= 3.6'
        python.architecture: x64
  steps:
  - ${{ if eq(parameters.vmImage, 'windows-2019') }}:
    - template: ./run-tests-windows.yml

  - ${{ if ne(parameters.vmImage, 'windows-2019') }}:
    - template: ./run-tests.yml
