parameters:
  vmImage:

jobs:
- job: Test_Primary
  displayName: Test Primary
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 4
    matrix:
      Python27:
        python.version: '2.7'
        python.architecture: x64
      ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}:
        # TODO remove once vs2017-win2016 has Python 3.7
        Python37:
          python.version: '>= 3.7.0-b2'
          python.architecture: x64
      ${{ if ne(parameters.vmImage, 'vs2017-win2016' )}}:
        Python37:
          python.version: '>= 3.7'
          python.architecture: x64
  steps:
  - ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}:
    - template: ./run-tests-windows.yml

  - ${{ if ne(parameters.vmImage, 'vs2017-win2016') }}:
    - template: ./run-tests.yml

- job: Test_Secondary
  displayName: Test python3.6
  # Run after Test_Primary so we don't devour time and jobs if tests are going to fail
  # dependsOn: Test_Primary
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 4
    matrix:
      Python36:
        python.version: '3.6'
        python.architecture: x64
  steps:
  - ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}:
    - template: ./run-tests-windows.yml

  - ${{ if ne(parameters.vmImage, 'vs2017-win2016') }}:
    - template: ./run-tests.yml
